FST-35 - adding authentication for admins
iprisakaru/FinalProjectScala pull request #4
Opened 2021-09-14 20:14 UTC by iprisakaru

2021-09-15 16:36 UTC, iprisakaru commented
Also fixed some bugs like making isPublic unnecessary field in creation, added DRY principles

2021-09-15 19:43 UTC, alexander-belyaev requested changes

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/model/dao/AdminsDAO.scala
> +  private def createQuery(entity: Admin): DBIOAction[Admin, NoStream, Effect.Read with Effect.Write with Effect.Transactional] = {
This method appears in literally every DAO.
Don't Repeat Yourself

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/model/dao/DirectorsFilmsDAO.scala
> +    directorsFilms.filter(e => e.film_id === id).delete
I belive there's no need to give a name to variable

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/model/dao/FilmsDAO.scala
>      result.flatMap(data => insertLinkedTables(data)).map(data => film.copy(actorsId = data(0), genresId = data(1), directorsId = data(2), countriesId = data(3)))
Magic numbers

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/model/dao/FilmsDAO.scala
> +    e.map(_.toOption)
Could be made a one-liner without declaring a variable

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/model/dao/FilmsDAO.scala
> +      genresDeleted <- genresFilmsDAO.deleteByFilmIdQuery(id).asTry
Try to set up  cascade deletes in database instead
Good that you spot a need to use transaction

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/utils/AdminsService.scala
> +    adminsDAO.insert(admin.copy(password = admin.password.bcrypt))
Looks good now

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/utils/FilmsService.scala
> +        createWithoutFilling(NewFilmWithId(None, data._1.name, Option(data._1.ageLimit.get), data._2._1, data._2._2._1, data._2._2._2._1, data._2._2._2._2._1, data._1.shortDescription, data._1.timing
How readable is data._2._2._2._1 from your point of view? What is the reason to use Tuple[Tuple[Tuple[Tuple[]]] datatype?

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/web/Routes.scala
> +        LOGGER.debug(s"Admin $user makes request")
What request?) 
Should you log request and response bodies as well?

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/web/api/FilmsApi.scala
> +          }
Formatting

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/web/api/GenresApi.scala
> +
formatting

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/web/api/auth/HTTPBasicAuth.scala
> +    def challenge = HttpChallenges.basic(realm)
Please make sure the standard browser dialog does not appear if I send the request via Postman with and without the Authentication header

2021-09-15 19:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/web/api/auth/HTTPBasicAuth.scala
> +    RouteService.adminsService.getPassword(username).map(pass=>{
formatting

2021-09-15 20:30 UTC, iprisakaru commented on src/main/scala/by/bsu/utils/FilmsService.scala
> +        createWithoutFilling(NewFilmWithId(None, data._1.name, Option(data._1.ageLimit.get), data._2._1, data._2._2._1, data._2._2._2._1, data._2._2._2._2._1, data._1.shortDescription, data._1.timing
To make Fututre[Some] and Future[Some] to Future[(Some,Some)[

2021-09-16 14:23 UTC, alexander-belyaev requested changes

2021-09-18 16:53 UTC, alexander-belyaev approved these changes

2021-09-18 16:54 UTC, merged