FST-10-36 - added oAuth 2.0 via Github and leaving comments only to users
iprisakaru/FinalProjectScala pull request #7
Opened 2021-10-02 19:07 UTC by iprisakaru

Added oAuth via Github. For example when you want to insert a comment.

2021-10-02 19:13 UTC, iprisakaru commented on build.sbt
> +  "org.apache.httpcomponents.client5" % "httpclient5" % "5.1",
library for getting components of URI

2021-10-04 09:43 UTC, alexander-belyaev requested changes

2021-10-04 09:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/model/dao/UsersDAO.scala
> +    LOGGER.debug(s"Inserting user ${user.ghLogin}")
Always give full names to variables. Your colleague could have troubles understanding what "gh" means
 githubLogin is much more clear

2021-10-04 09:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/utils/AuthService.scala
> +      uri = s"https://github.com/login/oauth/access_token?client_id=5c481d41c1df3a0cc298&client_secret=c674651120f1a7e4431ecca404f273552e3c18cd&code=$code")
Do you think it makes sense to move github API urls to configuration?
I imagine a need to replace real URL with the mocked one in some circumstances

2021-10-04 09:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/utils/AuthService.scala
> +    val uriFut = tokenFut.map(data => s"?$data")
what is "fut"?

2021-10-04 09:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/utils/AuthService.scala
> +    val accessToken = params.map(_.get(0)).map(data => {
why 0?

2021-10-04 09:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/utils/AuthService.scala
> +    val request = HttpRequest(HttpMethods.GET, uri = "https://api.github.com/user").addHeader(headerAuth)
Move URI to configuration

2021-10-04 09:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/utils/AuthService.scala
> +    val request = HttpRequest(HttpMethods.GET, uri = "https://www.googleapis.com/oauth2/v2/userinfo").addHeader(headerAuth)
Move to config

2021-10-04 09:43 UTC, alexander-belyaev commented on src/main/scala/by/bsu/utils/GithubUserService.scala
> +  def checkGithubUserByNode(githubUser: User) ={
formatting

2021-10-04 11:31 UTC, alexander-belyaev approved these changes

2021-10-07 18:40 UTC, merged